title: KEVDOUGFUL
email: kevdougful@gmail.com
description: >
  The public key to my brain.  Read on and you'll soon be able to encrypt
  knowledge into something only the two of us will understand.  Read further
  and you'll be able to verify my thoughts' signatures _sin nombre_, where ever
  you might find them.
baseurl: ""
url: "http://www.kevdougful.com"
twitter_username: kevdougful
github_username:  kevdougful

# Build settings
markdown: kramdown
theme: minima
